CRITICAL - 2023-10-12 12:15:38 --> App\Controllers\TestDB::index(): Return value must be of type string, none returned
in APPPATH\Controllers\TestDB.php on line 13.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:20:42 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:20:42 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:20:45 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM r...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:20:45 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT * FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:21:11 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:21:11 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:05 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:05 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:12 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:12 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:14 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:14 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:15 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:15 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:23 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:23 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:24 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:24 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:22:57 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:22:57 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:23:50 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:23:54 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:24:17 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:24:18 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:24:18 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:24:18 --> Class "CodeIgniter\Database\MySQL\Connection" not found
in SYSTEMPATH\Database\Database.php on line 137.
 1 SYSTEMPATH\Database\Database.php(55): CodeIgniter\Database\Database->initDriver('MySQL', 'Connection', [...])
 2 SYSTEMPATH\Database\Config.php(81): CodeIgniter\Database\Database->load([...], 'default')
 3 SYSTEMPATH\Common.php(363): CodeIgniter\Database\Config::connect('default', true)
 4 APPPATH\Controllers\TestDB.php(11): db_connect()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:24:25 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', '', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:24:25 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:26:38 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', 'hellskitchen', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', 'hellskitchen', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:26:38 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:27:00 --> Error connecting to the database: ErrorException: mysqli::real_connect(): php_network_getaddresses: getaddrinfo for hellskitchen failed: Hï¿½te inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'C:\\laragon\\www\\...', 185)
#1 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', 'hellskitchen', 3306, '', 0)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#4 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}

Next mysqli_sql_exception: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:185
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(185): mysqli->real_connect('hellskitchen', 'root', '', 'hellskitchen', 3306, '', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu.  in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2023-10-12 12:27:00 --> Unable to connect to the database.
Main connection [MySQLi]: php_network_getaddresses: getaddrinfo for hellskitchen failed: Hôte inconnu. 
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 3 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 4 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 5 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 12:27:48 --> mysqli_sql_exception: Unknown column 'nom' in 'field list' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT nom FROM...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT nom FROM...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT nom FROM...')
#3 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM...')
#4 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#5 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#6 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2023-10-12 12:27:48 --> Unknown column 'nom' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 APPPATH\Controllers\TestDB.php(12): CodeIgniter\Database\BaseConnection->query('SELECT nom FROM recettes LIMIT 1')
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:28:17 --> Undefined property: stdClass::$nom
in APPPATH\Controllers\TestDB.php on line 14.
 1 APPPATH\Controllers\TestDB.php(14): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: stdClass::$nom', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 14)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:42:23 --> Call to undefined function App\Controllers\find()
in APPPATH\Controllers\TestDB.php on line 16.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:09 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:10 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:11 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:12 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:12 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:12 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:12 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:12 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:13 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:13 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:13 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:13 --> Undefined variable $nomRecette
in APPPATH\Controllers\TestDB.php on line 16.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $nomRecette', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 16)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:21 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:49 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:50 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:50 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:50 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:50 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:50 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:51 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:51 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:51 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:43:51 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:22 --> Call to a member function getRow() on array
in APPPATH\Controllers\TestDB.php on line 17.
 1 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 2 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 3 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:28 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:29 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:29 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:29 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:29 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:30 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:31 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:31 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:31 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:31 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:44 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:44 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:45 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:44:45 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:45:31 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:45:36 --> Undefined array key 0
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined array key 0', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 12:45:41 --> Array to string conversion
in APPPATH\Controllers\TestDB.php on line 17.
 1 APPPATH\Controllers\TestDB.php(17): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'C:\\laragon\\www\\ci-atelier3\\app\\Controllers\\TestDB.php', 17)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 13:04:30 --> Cannot declare class App\Models\RecetteModel, because the name is already in use
in APPPATH\Models\IngredientModel.php on line 7.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2023-10-12 13:10:04 --> Too few arguments to function CodeIgniter\BaseModel::save(), 0 passed in C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php on line 16 and exactly 1 expected
in SYSTEMPATH\BaseModel.php on line 689.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\BaseModel->save()
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 13:15:15 --> Too few arguments to function CodeIgniter\BaseModel::save(), 0 passed in C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php on line 16 and exactly 1 expected
in SYSTEMPATH\BaseModel.php on line 689.
 1 APPPATH\Controllers\TestDB.php(16): CodeIgniter\BaseModel->save()
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 13:16:30 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(916): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\TestDB.php(16): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:02 --> mysqli_sql_exception: Unknown column 'recettes.deleted_at' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(563): CodeIgniter\Model->doFind(false, NULL)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(26): CodeIgniter\BaseModel->find()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:02 --> Unknown column 'recettes.deleted_at' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `recettes`
WHERE `idRecette` = :idRecette:
AND `recettes`.`deleted_at` IS NULL', [...], false)
 2 SYSTEMPATH\Model.php(199): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(563): CodeIgniter\Model->doFind(false, null)
 4 APPPATH\Controllers\TestDB.php(26): CodeIgniter\BaseModel->find()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:17 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:17 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:35 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:35 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:47 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:47 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:48 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:48 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:19:48 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:19:48 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:21 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:21 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:22 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:22 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:50 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:50 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:51 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:51 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:51 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:51 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:51 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:51 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:51 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:51 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:20:56 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:20:56 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:21:07 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:21:07 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(34): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:22:03 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:22:03 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:22:19 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:22:19 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:22:41 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:22:41 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-10-12 13:23:24 --> mysqli_sql_exception: Unknown column 'nomRecette' in 'where clause' in C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\ci-atelier3\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT *\nFROM `...', 0)
#1 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 C:\laragon\www\ci-atelier3\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 C:\laragon\www\ci-atelier3\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\laragon\www\ci-atelier3\system\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
#5 C:\laragon\www\ci-atelier3\system\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\laragon\www\ci-atelier3\app\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
#7 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(919): App\Controllers\TestDB->index()
#8 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
#9 C:\laragon\www\ci-atelier3\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\laragon\www\ci-atelier3\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-10-12 13:23:24 --> Unknown column 'nomRecette' in 'where clause'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `ingredients`
WHERE `nomRecette` = :nomRecette:', [...], false)
 2 SYSTEMPATH\Model.php(237): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH\BaseModel.php(624): CodeIgniter\Model->doFindAll(0, 0)
 4 APPPATH\Controllers\TestDB.php(35): CodeIgniter\BaseModel->findAll()
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-10-12 13:33:11 --> There is no data to update.
in SYSTEMPATH\BaseModel.php on line 1724.
 1 SYSTEMPATH\BaseModel.php(1724): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('update')
 2 SYSTEMPATH\BaseModel.php(916): CodeIgniter\BaseModel->transformDataToArray(null, 'update')
 3 SYSTEMPATH\Model.php(776): CodeIgniter\BaseModel->update([...], null)
 4 APPPATH\Controllers\TestDB.php(21): CodeIgniter\Model->update([...])
 5 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\TestDB->index()
 6 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\TestDB))
 7 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
